// shared by core and metadata, public + internal

import type { LanguageModelUsage } from "ai"

/**
 * Represents the token usage metadata attached to a message.
 *
 * This metadata is generated by AI SDK Token Usage and includes
 * both the total token usage reported by the model and the
 * canonical model identifier.
 *
 * Used by the `messageMetadata` callback in
 * `toUIMessageStreamResponse` to store cost and usage information
 * for each completed model response.
 */
export type TokenUsageMetadata = {
  /** The total token usage for the model response, as reported by the provider. */
  totalUsage: LanguageModelUsage
  /** The canonical model identifier (e.g., "openai/gpt-5"). */
  canonicalSlug: string
}
